### ISSUE TITLE
More Results???

### ISSUE THREAD

**Issue by ghost** [LowLevelSubmarine/YouTubeMusicLibrary#1]
Hi i have been using the library with my project with credits of course... and i absolutely love it..

BUT.... is there any way i can load more than 20 results for Songs?? if not could you possibly implement it??

Thanks for your hard work..
I4A

**Comment by LowLevelSubmarine** [comment]
Im afraid, I currently have other priorities with the library, but it's not like I wouldn't also want such a feature. I will take a look at it.

**Comment by LowLevelSubmarine** [comment]
If you want, you could fork the project and add the method yourself. I'd pull the changes thankfully.

**Comment by ghost** [comment]
was going to add the method to the project today but for some reason the api is not working i have tried for the last few hours to figure out why......??

here is the error log >>>

W/System.err: java.io.FileNotFoundException: https://s.ytimg.com/yts/jsbin/null
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.decipherSignature(YouTubeExtractor.java:436)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:394)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:196)
W/System.err:     at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by dieckyawsm** [comment]
How to implemention this respontory?

**Comment by LowLevelSubmarine** [comment]
[Take a look at my SearchTest on the code side of things](https://github.com/LowLevelSubmarine/YouTubeMusicLibrary/blob/master/src/test/java/SearchTest.java)
and add the project via [![](https://jitpack.io/v/LowLevelSubmarine/YouTubeMusicLibrary.svg)](https://jitpack.io/#LowLevelSubmarine/YouTubeMusicLibrary)

I will close the issue for now, as the original question is already solved with the new version of YTML
